apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udo.fullname" . }}
  labels:
    {{- include "udo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "udo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "udo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/udo"]
          args:
            - "--input"
            - "kafka://{{ .Values.config.kafka.brokers }}/{{ .Values.config.kafka.group_id }}/{{ .Values.config.kafka.topic }}"
            - "--output"
            - "s3://my-bucket/output"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
